### PR TITLE
0506 Demo For Daniel

### PR DESCRIPTION
**Pull request by summer7xinting**
Demo steps:
- make directories in /tmp: `/tmp/demo/input`
- put any GPM file in `/tmp/demo/input`: downloaded from [here](https://data-catalog.mint.isi.edu/datasets/ea0e86f3-9470-4e7e-a581-df85b4a7075d)
- run command: `docker run --rm -p 5000:5000 -v $(pwd):/ws -v /tmp:/tmp -it mint_dt bash /ws/examples/topoflow4/run_climate.sh`
- check `/tmp/demo/output`: should produce `climate_all.rti` and `climate_all.rts` correctly
Note: previous config file and adapter variable naming is out of place so I fixed that ;)

### CODE REVIEW

**Comment by minhptx** [comment]
@dgarijo @sirspock please review and let us know if this is what you guys want.

**Comment by dgarijo** [comment]
Thanks Minh, we will take a look and let you know. One question: why is this the PR blocked? Am I supposed to review and accept it?

**Comment by minhptx** [comment]
> Thanks Minh, we will take a look and let you know. One question: why is this the PR blocked? Am I supposed to review and accept it?

I added you as a reviewer. You can review and approve the the PR.

**Comment by dgarijo** [comment]
I reviewed it and it looks good. I will give it a try.

**Comment by dgarijo** [comment]
@summer7xinting @minhptx one question: The output file is specified to be climate_all.rts. However, there is another one generated (climate_all.rti). Without the rti file, the rts won't work. Why is it not then specified as output file?

**Comment by minhptx** [comment]
@dgarijo I see. I'll ask Xinting to fix this. When Scott asked us to run his transformation, he only need the rts file. That's why we assume only the rts files are needed.

**Comment by summer7xinting** [comment]
I suppose we need to specify output file path and file name (without rts and rti extension)?

**Comment by dgarijo** [comment]
No, I think both are in tandem. Also, the input to the topoflow model is a zipped file. Is it possible to create it as a zipped file at the end? This is a technicality, but it would make it ready to plug in the model

**Comment by summer7xinting** [comment]
In the case of generating a zipped file, it's reasonable to give a `path/climate_all.zip` and the adapter will take care of the rest.

**Comment by dgarijo** [comment]
Is it possible to have it as part of this example?

**Comment by summer7xinting** [comment]
Creating another PR now

**Pull request merged**
