### PR TITLE
0506 Demo: Zipped Result

### PR DESCRIPTION
**Pull request by summer7xinting**
As per [this](https://github.com/mintproject/MINT-Transformation/pull/66) PR:
**now the rts and rti file will live in specified tmp dir and the zipped file will be the specified output file.** 
I modified the yml as well so please try:
- make directory in /tmp: `/tmp/demo/input`
- put any GPM file in `/tmp/demo/input`: downloaded from [here](https://drive.google.com/file/d/1NQsWHwctdiF8UfMGqaxuc9lpDSVxOcvG/view?usp=sharing)
  - Note that for some reason, the files downloaded from [here](https://data-catalog.mint.isi.edu/datasets/ea0e86f3-9470-4e7e-a581-df85b4a7075d) could have empty size. Will investigate more into this issue. 
  - All GPM files are hosted on [here](https://files.mint.isi.edu/apps/files/?dir=/&view=sharinglinks)
- run command: `docker run --rm -p 5000:5000 -v $(pwd):/ws -v /tmp:/tmp -it mint_dt bash /ws/examples/topoflow4/run_climate.sh`
- check `/tmp/demo/output`: should produce `climate_all.zip` correctly (I checked the diff: they are the same)

### CODE REVIEW

**Comment by dgarijo** [comment]
@summer7xinting have you checked: https://github.com/mintproject/MINT-Transformation/issues/65 ? We cannot build the image

**Comment by dgarijo** [comment]
This looks good to me. I look forward to testing it out.

**Comment by sirspock** [comment]
The instructions doesn't works.
https://asciinema.org/a/MxNds9Foi0BL3WlVd1QN7H9tX

**Comment by sirspock** [comment]
In the DAME context, the user doesn't have the MINT-Transformation repository. 
The image must have all the files.

**Comment by sirspock** [comment]
Your instructions refers to the file:  /ws/examples/topoflow4/run_climate.sh

But, I can't find it

❯ ls examples/topoflow4/
resources  topoflow_climate_per_month.yml  topoflow_climate.yml  topoflow_soil.yml

**Comment by sirspock** [comment]
The correct command is:

```bash
docker run --rm -v $(pwd):/ws -v /tmp:/tmp mint_dt examples/topoflow4/topoflow_climate.yml
```

The instructions are outdated

**Comment by dgarijo** [comment]
@summer7xinting @minhptx I have a question on the following:
```
DEM_bounds: "23.995416666666, 6.532916666667, 28.020416666666, 9.566250000000"
DEM_xres_arcsecs: "30"
DEM_yres_arcsecs: "30"
```
DEM_bound: Is this described as the upper left and bottom right of the box? And is it LAT, LON?

xres, yres: is it in seconds? I assume it is, because of arcsec.

**Comment by minhptx** [comment]
@dgarijo I think the order is "lon_min, lat_min, lon_max, lat_max" and the resolution are in arcseconds.

**Comment by dgarijo** [comment]
@minhptx do you think, or do you know for sure? This is critical info for using the transformation :)

**Comment by minhptx** [comment]
@binh-vu can you confirm this ?

> @dgarijo I think the order is "lon_min, lat_min, lon_max, lat_max" and the resolution are in arcseconds.

**Pull request merged**
